var a=5;
console.log(typeof(a));
var b=true;
console.log(typeof(b));
var c="vaishu";
console.log(typeof(c));
var d={firstName:"vaishu", lastName:"jasper"};
console.log(typeof(d));
var d=50.67;
console.log(typeof(d));
var a=8;
var b=6;
var c=8;
console.log((a==b));
console.log((a==c));
var person = {firstName:"John", lastName:"Doe", age:50, eyeColor:"blue"};
console.log(typeof(null));
var x;
console.log(typeof(x));
